gitlab-update:
  stage: deploy
  script:
    - curl 'https://cdn.jsdelivr.net/gh/fernvenue/chn-cidr-list@master/updater.sh' -o ./gitlab-updater.sh
    - sed -i 's|GITHUB|GITLAB|g' ./gitlab-updater.sh
    - sed -i 's|github|gitlab|g' ./gitlab-updater.sh
    - chmod +x ./gitlab-updater.sh
    - ./gitlab-updater.sh

github-update:
  stage: deploy
  script:
    - curl 'https://cdn.jsdelivr.net/gh/fernvenue/chn-cidr-list@master/updater.sh' -o ./github-updater.sh
    - chmod +x ./github-updater.sh
    - ./github-updater.sh
